<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Valeria (Vale) Cardenas' Personal Website</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            line-height: 1.6;
            color: #333;
            background-color: #f4f4f4;
        }
        .container {
            max-width: 800px;
            margin: auto;
            overflow: hidden;
            padding: 0 20px;
        }
        header {
            background: #333;
            color: #fff;
            padding-top: 30px;
            min-height: 70px;
            border-bottom: #0779e4 3px solid;
        }
        header h1, header p {
            text-align: center;
            margin: 0;
        }
        .content, .projects {
            padding: 20px;
            background: #fff;
            margin: 20px 0;
        }
        .content h2, .content p, .projects h2, .projects p, .projects ul {
            margin: 0 0 20px 0;
        }
        .projects a {
            color: #0779e4;
            text-decoration: none;
        }
        .footer {
            text-align: center;
            padding: 20px;
            background: #333;
            color: #fff;
        }
        ul {
            list-style-type: none;
            padding: 0;
        }
        li {
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <header>
        <div class="container">
            <h1>Hi, I'm Valeria (Vale) Cardenas</h1>
            <p>Welcome to my personal website!</p>
        </div>
    </header>

    <section class="content container">
        <h2>About Me</h2>
        <p>Hey there, I'm Valeria Cardenas. At my core, I'm driven by an insatiable curiosity, whether I'm experimenting in the kitchen, diving into data analysis for my consulting projects, or building something new in my entrepreneurial ventures.</p>
    </section>

    <section class="content container">
        <h2>Contact</h2>
        <p>You can contact me at <a href="mailto:valecardenas24@gmail.com">valecardenas24@gmail.com</a>.</p>
    </section>

    <section class="projects container">
        <h2>My Creations</h2>
        <ul>
            <li><strong>ValeCooks:</strong> I started a weekly 📧 newsletter where I try out new recipes and share my discoveries, along with some of my all-time favorites🌟. This newsletter is your shortcut to finding great recipes 🍲 without the trial and error. Check out my first posts at <a href="https://valecooks.beehiiv.com" target="_blank">valecooks.beehiiv.com</a>.</li>
            <li><strong>YouTube Channel for ValeCooks:</strong> Visit my YouTube Channel for more insights and recipe videos at <a href="https://www.youtube.com/channel/UCCfDgSi9UmPBuWicd1FvxrQ" target="_blank">youtube.com/channel/UCCfDgSi9UmPBuWicd1FvxrQ</a>.</li>
        </ul>
        <h3>GPT Projects</h3>
        <ul>
            <li><strong>Qualitative Data Analysis:</strong> Explore the tool at <a href="https://chat.openai.com/g/g-hBb8iIFDc-qualitative-data-analysis" target="_blank">chat.openai.com/g/g-hBb8iIFDc-qualitative-data-analysis</a>.</li>
            <li><strong>Meal Plan Maestro:</strong> Discover the project here <a href="https://chat.openai.com/g/g-ttFBfxpoP-meal-plan-maestro" target="_blank">chat.openai.com/g/g-ttFBfxpoP-meal-plan-maestro</a>.</li>
        </ul>
    </section>

    <footer class="footer">
        <p>This page was generated by GitHub Pages. Theme customization and content are created by Valeria (Vale) Cardenas.</p>
    </footer>
</body>
</html>
